DELAY_DURATION_IN_MILLIS: "{{ lookup('env','DELAY_DURATION_IN_MILLIS') }}"
NETWORK_SIMULATION_DURATION: "{{ lookup('env','NETWORK_SIMULATION_DURATION') }}"

CONTAINER_STATE: "{{ lookup('env','CONTAINER_STATE') }}"
CONTAINER_NAMES: "{{ lookup('env','CONTAINER_NAMES') }}"